spring.application.name=rag-tools

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,env,beans,prometheus
management.endpoint.health.show-details=always
server.port=8082

spring.ai.mcp.server.name=rag-tools
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC

app.s3.bucket-name=${S3_BUCKET_NAME:rag-documents-lexoft-2026}
app.s3.region=${AWS_REGION:us-east-1}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/rag-assistant}
